[project]
name = "infinite-mac"
version = "0.1.0"
description = "Infinite Mac build tooling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "machfs @ git+https://github.com/mihaip/machfs.git@7b6e5acf189383cd0154bfb47834c1394b3a1bf4",
    "beautifulsoup4==4.12.2",
    "Pillow>=12.3.0",
    "xattr==1.1.4",
]
